
// scripts/seed-db.ts
import { MongoClient } from 'mongodb';
import dotenv from 'dotenv';
import type { Product } from '@/types';

// Load environment variables from .env.local
dotenv.config({ path: '.env.local' });

const productsToSeed: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Lits (8)
  {
    name: 'IKEA HEMNES Lit 2',
    shortDescription: 'Lit double HEMNES classique et robuste.',
    description: 'Un lit double HEMNES classique et robuste d\'IKEA, avec une tête de lit haute. Parfait pour un style intemporel et une chambre accueillante.',
    price: 329.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/020_IKEA_HEMNES_bed_2/IKEA_HEMNES_bed_2_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Classique',
    rating: 4.4,
    stock: 45,
    colors: ['Blanc', 'Noir-brun'],
    materials: ['Pin massif', 'Acrylique'],
    dimensions: '170cm L x 211cm P x 120cm H (couchage 160x200)',
  },
  {
    name: 'IKEA Malm Lit',
    shortDescription: 'Lit IKEA Malm au design épuré.',
    description: 'Lit IKEA Malm avec un design épuré et des lignes droites. Offre des rangements optionnels sous le lit pour optimiser l\'espace.',
    price: 279.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/081_IKEA_Malm_Bed/IKEA_Malm_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Minimaliste',
    rating: 4.2,
    stock: 50,
    colors: ['Blanc', 'Plaqué chêne blanchi', 'Noir-brun'],
    materials: ['Panneau de particules', 'Fibre de bois'],
    dimensions: '176cm L x 209cm P x 100cm H (couchage 160x200)',
  },
  {
    name: 'Roche Bobois Bubble Lit',
    shortDescription: 'Lit Bubble Roche Bobois, design audacieux.',
    description: 'Le lit Bubble de Roche Bobois, un design audacieux et confortable avec ses formes organiques et son revêtement en tissu Techno 3D. Une pièce maîtresse.',
    price: 4500.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Roche-Bobois/026_Roche-Bobois_Bubble_Bed/Roche-Bobois_Bubble_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Moderne',
    rating: 4.9,
    stock: 10,
    colors: ['Rose Poudré', 'Gris Perle', 'Jaune Safran'],
    materials: ['Tissu Techno 3D', 'Mousse HR', 'Structure bois'],
    dimensions: 'Taille Queen, approx. 180cm L x 220cm P x 90cm H',
  },
  {
    name: 'Natuzzi Fenice Lit',
    shortDescription: 'Lit Fenice Natuzzi Italia, élégance et confort.',
    description: 'Lit Fenice de Natuzzi Italia, alliant élégance et confort avec une tête de lit capitonnée et des finitions soignées. Luxe italien.',
    price: 3800.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Natuzzi/001_Natuzzi_Fenice_Bed/Natuzzi_Fenice_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Contemporain',
    rating: 4.8,
    stock: 12,
    colors: ['Cuir Beige Clair', 'Tissu Gris Foncé'],
    materials: ['Cuir véritable', 'Tissu de haute qualité', 'Bois massif'],
    dimensions: 'Taille King, approx. 200cm L x 225cm P x 110cm H',
  },
  {
    name: 'IKEA HEMNES Lit',
    shortDescription: 'Structure de lit HEMNES simple et élégante.',
    description: 'Structure de lit HEMNES d\'IKEA, simple et élégante, en pin massif. Un classique intemporel pour une chambre cosy et chaleureuse.',
    price: 249.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/019_IKEA_HEMNES_bed/IKEA_HEMNES_bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Classique',
    rating: 4.3,
    stock: 60,
    colors: ['Blanc', 'Noir-brun', 'Gris Clair'],
    materials: ['Pin massif teinté'],
    dimensions: '150cm L x 211cm P x 120cm H (couchage 140x200)',
  },
  {
    name: 'Minotti Andersen Quilt Lit',
    shortDescription: 'Lit Andersen Quilt Minotti, design sophistiqué.',
    description: 'Lit Andersen Quilt par Minotti, caractérisé par une tête de lit matelassée raffinée et un design sophistiqué. Confort et élégance suprêmes.',
    price: 5200.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Minotti/007_Minotti_Andersen_Quilt_Bed/Minotti_Andersen_Quilt_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Contemporain',
    rating: 4.9,
    stock: 7,
    colors: ['Tissu Taupe Chiné', 'Velours Bleu Profond', 'Cuir Naturel'],
    materials: ['Tissu haut de gamme', 'Structure métallique', 'Bois rembourré'],
    dimensions: 'Taille King, approx. 210cm L x 230cm P x 105cm H',
  },
  {
    name: 'Lit en métal vintage victorien',
    shortDescription: 'Charmant lit en métal style victorien.',
    description: 'Un charmant lit en métal de style victorien, avec des détails ornementaux. Idéal pour une ambiance romantique et rétro, pour une personne.',
    price: 450.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/172_Generic_Victorian_Vintage_Twin_Size_Metal_Bed/Generic_Victorian_Vintage_Twin_Size_Metal_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Vintage',
    rating: 4.6,
    stock: 25,
    colors: ['Noir Antique Mat', 'Blanc Crème Brillant'],
    materials: ['Métal forgé, finition poudrée'],
    dimensions: '100cm L x 200cm P x 115cm H (couchage 90x190)',
  },
  {
    name: 'Savio Firmino 3058 Lit',
    shortDescription: 'Lit Savio Firmino, artisanat florentin luxueux.',
    description: 'Lit 3058 de Savio Firmino, une pièce d\'exception avec des sculptures faites à la main et des finitions luxueuses. Un chef-d\'œuvre de l\'artisanat florentin.',
    price: 8900.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Savio-Firmino/006_Savio-Firmino_3058_Bed/Savio-Firmino_3058_Bed_1000_0001-551x551.webp',
    category: 'Lits',
    style: 'Classique',
    rating: 5.0,
    stock: 5,
    colors: ['Bois Naturel Finition Or vieilli', 'Laqué Blanc Perle avec détails argentés'],
    materials: ['Bois précieux sculpté à la main', 'Feuille d\'or ou d\'argent', 'Tissus nobles'],
    dimensions: 'Taille King/Super King, dimensions sur mesure disponibles',
  },
  // Canapés (8)
  {
    name: 'Roche Bobois Bubble Grand canapé',
    shortDescription: 'Canapé Bubble Roche Bobois, design iconique.',
    description: 'Un design iconique et ludique, offrant un confort enveloppant avec ses formes arrondies. Parfait pour un intérieur contemporain et audacieux. Un véritable appel à la détente.',
    price: 3499.99,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Roche-Bobois/003_Roche-Bobois_Bubble_Large_Sofa/Roche-Bobois_Bubble_Large_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Moderne',
    rating: 4.8,
    stock: 15,
    colors: ['Rose Poudré', 'Gris Perle', 'Bleu Canard'],
    materials: ['Tissu Techno 3D', 'Mousse HR'],
    dimensions: '248cm L x 132cm P x 77cm H',
  },
  {
    name: 'Chesterfield Canapé',
    shortDescription: 'Canapé Chesterfield, élégance intemporelle.',
    description: 'L\'élégance intemporelle du style Chesterfield, avec son capitonnage profond caractéristique et ses accoudoirs enroulés. Une pièce de caractère en cuir véritable.',
    price: 2190.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/340_Chesterfield_Sofa/Chesterfield_Sofa_600_lq_0001-551x551.webp',
    category: 'Canapés',
    style: 'Classique',
    rating: 4.7,
    stock: 22,
    colors: ['Marron Chocolat', 'Vert Anglais', 'Bordeaux'],
    materials: ['Cuir Pleine Fleur', 'Bois Massif'],
    dimensions: '215cm L x 95cm P x 78cm H',
  },
  {
    name: 'Canapé marocain',
    shortDescription: 'Canapé marocain, ambiance chaleureuse.',
    description: 'Un canapé d\'inspiration marocaine, invitant à la convivialité avec ses assises basses, ses coussins colorés et ses motifs orientaux. Parfait pour une ambiance chaleureuse.',
    price: 1750.50,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/155_Generic_Moroccan_Sofa/Generic_Moroccan_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Bohème',
    rating: 4.5,
    stock: 18,
    colors: ['Rouge Carmin', 'Orange Safran', 'Bleu Majorelle', 'Multicolore'],
    materials: ['Tissu Damassé', 'Bois de Cèdre', 'Velours'],
    dimensions: '260cm L x 85cm P x 70cm H',
  },
  {
    name: 'IKEA Soderhamn Sofa',
    shortDescription: 'Canapé Soderhamn IKEA, modulable et confortable.',
    description: 'Modulable et confortable, le canapé Soderhamn d\'IKEA offre une assise profonde et des coussins moelleux. Son design épuré s\'intègre facilement à divers styles d\'intérieurs.',
    price: 799.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/094_IKEA_Soderhamn_Sofa/IKEA_Soderhamn_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Scandinave',
    rating: 4.3,
    stock: 35,
    colors: ['Gris Foncé', 'Turquoise', 'Blanc Cassé'],
    materials: ['Polyester', 'Contreplaqué', 'Acier'],
    dimensions: '198cm L x 99cm P x 83cm H',
  },
  {
    name: 'Ethnicraft N701 Sofa',
    shortDescription: 'Canapé N701 Ethnicraft, design minimaliste.',
    description: 'Le canapé N701 d\'Ethnicraft se distingue par ses lignes minimalistes et son design modulaire. Disponible en plusieurs éléments pour créer une configuration personnalisée.',
    price: 2450.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Ethnicraft/001_Ethnicraft_N701_Sofa/Ethnicraft_N701_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Minimaliste',
    rating: 4.6,
    stock: 12,
    colors: ['Beige', 'Gris Anthracite', 'Bleu Nuit'],
    materials: ['Tissu de lin', 'Bois Massif'],
    dimensions: '210cm L x 91cm P x 76cm H (pour le 3 places)',
  },
  {
    name: 'BoConcept Bergamo Sofa',
    shortDescription: 'Canapé Bergamo BoConcept, design italien.',
    description: 'Le canapé Bergamo de BoConcept allie design italien et confort exceptionnel. Ses lignes organiques et ses détails raffinés en font une pièce maîtresse de votre salon.',
    price: 3200.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/BoConcept/023_BoConcept_Bergamo_Sofa/BoConcept_Bergamo_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Contemporain',
    rating: 4.9,
    stock: 8,
    colors: ['Cuir Camel', 'Tissu Gris Chiné', 'Velours Vert Forêt'],
    materials: ['Cuir', 'Tissu', 'Piètement Métal'],
    dimensions: '240cm L x 105cm P x 70cm H',
  },
  {
    name: 'Sarah Ellison Muse Sofa',
    shortDescription: 'Canapé Muse Sarah Ellison, allure sculpturale.',
    description: 'Avec ses courbes douces et son allure sculpturale, le canapé Muse de Sarah Ellison est une invitation à la relaxation. Un design australien contemporain et élégant.',
    price: 2950.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Sarah-Ellison/001_Sarah-Ellison_Muse_Sofa/Sarah-Ellison_Muse_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Moderne',
    rating: 4.7,
    stock: 10,
    colors: ['Crème Bouclette', 'Velours Terracotta', 'Lin Naturel'],
    materials: ['Tissu Bouclette', 'Velours', 'Lin'],
    dimensions: '220cm L x 100cm P x 75cm H',
  },
  {
    name: 'IKEA Friheten Sofa',
    shortDescription: 'Canapé Friheten IKEA, convertible et pratique.',
    description: 'Le canapé convertible Friheten d\'IKEA est une solution pratique et polyvalente. Il se transforme facilement en lit et dispose d\'un espace de rangement intégré.',
    price: 549.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/110_IKEA_Friheten_Sofa/IKEA_Friheten_Sofa_1000_0001-551x551.webp',
    category: 'Canapés',
    style: 'Fonctionnel',
    rating: 4.1,
    stock: 40,
    colors: ['Gris Skiftebo', 'Noir Hyllie', 'Beige Foncé'],
    materials: ['Polyester', 'Bois Massif', 'Panneau de particules'],
    dimensions: '230cm L x 151cm P (méridienne) x 66cm H',
  },
  // Chaises (8)
  {
    name: 'Cassina Dudet Chaise',
    shortDescription: 'Chaise Dudet Cassina, confort moelleux.',
    description: 'La chaise Dudet de Cassina, design Patricia Urquiola, offre un confort moelleux avec une esthétique ludique et contemporaine. Ses formes arrondies invitent à la détente.',
    price: 850.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Cassina/004_Cassina_Dudet_Chair/Cassina_Dudet_Chair_1000_0001-551x551.webp',
    category: 'Chaises',
    style: 'Moderne',
    rating: 4.7,
    stock: 20,
    colors: ['Tissu Jaune Curry', 'Velours Vert Olive', 'Cuir Cognac'],
    materials: ['Mousse polyuréthane', 'Revêtement tissu ou cuir', 'Structure interne en métal'],
    dimensions: '60cm L x 55cm P x 78cm H',
  },
  {
    name: 'Mawu Chaise',
    shortDescription: 'Chaise Mawu, design sculptural organique.',
    description: 'Chaise Mawu au design sculptural et organique, souvent réalisée en bois avec des lignes fluides. Une pièce artistique qui attire le regard.',
    price: 680.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/188_Generic_Mawu_Chair/Generic_Mawu_Chair_1000_0001-551x551.webp',
    category: 'Chaises',
    style: 'Contemporain',
    rating: 4.5,
    stock: 15,
    colors: ['Bois Naturel Clair', 'Bois Teinté Noyer'],
    materials: ['Bois massif (Chêne, Noyer)'],
    dimensions: '50cm L x 52cm P x 80cm H',
  },
  {
    name: 'IKEA Lisabo Chaise',
    shortDescription: 'Chaise Lisabo IKEA, simple et élégante.',
    description: 'Chaise IKEA Lisabo, simple et élégante avec un design épuré scandinave. Fabriquée en frêne, elle est légère et robuste.',
    price: 59.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/113_IKEA_Lisabo_Chair/IKEA_Lisabo_Chair_1000_0001-551x551.webp',
    category: 'Chaises',
    style: 'Scandinave',
    rating: 4.2,
    stock: 70,
    colors: ['Frêne Naturel'],
    materials: ['Frêne massif', 'Vernis acrylique incolore'],
    dimensions: '44cm L x 51cm P x 80cm H',
  },
  {
    name: 'Magis Chair One',
    shortDescription: 'Chair One Magis, icône design industriel.',
    description: 'La Chair One de Magis, design Konstantin Grcic, est une icône du design industriel. Sa structure en fonte d\'aluminium lui confère un look unique et une grande durabilité, utilisable en intérieur comme en extérieur.',
    price: 350.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/355_Chair_One/Chair_One_600_lq_0001-551x551.webp',
    category: 'Chaises',
    style: 'Industriel',
    rating: 4.9,
    stock: 25,
    colors: ['Noir', 'Blanc', 'Rouge', 'Aluminium poli'],
    materials: ['Fonte d\'aluminium verni ou poli'],
    dimensions: '55cm L x 59cm P x 82cm H',
  },
  {
    name: 'Cassina Capitol Chaise de Bureau',
    shortDescription: 'Chaise bureau Capitol Cassina, élégance et fonction.',
    description: 'La chaise de bureau Capitol de Cassina, inspirée des designs de Pierre Jeanneret, allie élégance et fonctionnalité. Structure en bois et assise confortable.',
    price: 1200.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Cassina/007_Cassina_Capitol_Office_Chair/Cassina_Capitol_Office_Chair_1000_0001-551x551.webp',
    category: 'Chaises',
    style: 'Moderne',
    rating: 4.8,
    stock: 12,
    colors: ['Bois de Teck Naturel, Tissu Beige', 'Bois Noir, Cuir Noir'],
    materials: ['Bois massif (Teck, Chêne)', 'Cuir', 'Tissu'],
    dimensions: '65cm L x 60cm P x 85cm H (ajustable)',
  },
  {
    name: 'Steelcase Think Chaise de Bureau',
    shortDescription: 'Chaise bureau Think Steelcase, confort intelligent.',
    description: 'La chaise de bureau Think de Steelcase est conçue pour un confort intelligent et durable. Elle s\'adapte intuitivement aux mouvements de l\'utilisateur.',
    price: 780.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Steelcase/003_Steelcase_Think_Offie_Chairs/Steelcase_Think_Offie_Chairs_1000_0001-551x551.webp',
    category: 'Chaises',
    style: 'Ergonomique',
    rating: 4.7,
    stock: 30,
    colors: ['Noir', 'Gris Platine', 'Bleu Cobalt'],
    materials: ['Plastique recyclé', 'Tissu technique', 'Aluminium'],
    dimensions: '72cm L x 60cm P x 100-113cm H (ajustable)',
  },
  {
    name: 'Acapulco Chaise',
    shortDescription: 'Chaise Acapulco, classique design mexicain.',
    description: 'La chaise Acapulco, un classique du design mexicain des années 50. Sa structure en acier et son tressage en fils de PVC la rendent confortable et résistante, idéale pour l\'extérieur.',
    price: 150.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/406_Acapulco_Chair/Acapulco_Chair_600_lq_0001-551x551.webp',
    category: 'Chaises',
    style: 'Vintage',
    rating: 4.6,
    stock: 40,
    colors: ['Noir', 'Blanc', 'Turquoise', 'Jaune'],
    materials: ['Acier', 'Fils de PVC'],
    dimensions: '73cm L x 80cm P x 88cm H',
  },
  {
    name: 'Chaise de jeu',
    shortDescription: 'Chaise de jeu ergonomique pour longues sessions.',
    description: 'Une chaise de jeu ergonomique conçue pour de longues sessions. Offre un soutien lombaire, des accoudoirs réglables et un design sportif.',
    price: 280.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/477_Gaming_Chair/Gaming_Chair_600_lq_0001-551x551.webp',
    category: 'Chaises',
    style: 'Moderne',
    rating: 4.4,
    stock: 35,
    colors: ['Noir/Rouge', 'Noir/Bleu', 'Blanc/Noir'],
    materials: ['Similicuir', 'Mousse haute densité', 'Nylon'],
    dimensions: '70cm L x 65cm P x 125-135cm H (ajustable)',
  },
  // Lampes (8)
  {
    name: 'West-Elm Olivia Lampe à Suspension',
    shortDescription: 'Lampe Olivia West Elm, élégance moderne.',
    description: 'Lampe à suspension Olivia de West Elm, avec un abat-jour en verre texturé et des accents en laiton. Apporte une touche d\'élégance moderne à n\'importe quel espace.',
    price: 199.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/West-Elm/009_West-Elm_Olivia_Pendant_Lamp/West-Elm_Olivia_Pendant_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Moderne',
    rating: 4.6,
    stock: 30,
    colors: ['Laiton Antique', 'Verre transparent'],
    materials: ['Verre', 'Métal'],
    dimensions: 'Abat-jour: 25cm Diam. x 30cm H',
  },
  {
    name: 'Lustre',
    shortDescription: 'Lustre classique, pampilles en cristal.',
    description: 'Un lustre classique avec de multiples branches et des pampilles en cristal. Idéal pour ajouter une touche de glamour et d\'opulence à une salle à manger ou un hall d\'entrée.',
    price: 450.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/417_Chandelier/Chandelier_600_lq_0001-551x551.webp',
    category: 'Lampes',
    style: 'Classique',
    rating: 4.8,
    stock: 15,
    colors: ['Cristal transparent', 'Structure dorée ou argentée'],
    materials: ['Cristal', 'Métal'],
    dimensions: '60cm Diam. x 70cm H (variable)',
  },
  {
    name: 'IKEA Ranarp Lampadaire',
    shortDescription: 'Lampadaire Ranarp IKEA, style industriel.',
    description: 'Lampadaire Ranarp d\'IKEA, avec un design inspiré de l\'époque industrielle. Tête et bras réglables pour diriger la lumière là où vous en avez besoin.',
    price: 49.99,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/080_IKEA_Ranarp_Lamp/IKEA_Ranarp_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Industriel',
    rating: 4.3,
    stock: 50,
    colors: ['Noir', 'Blanc cassé'],
    materials: ['Acier', 'Plastique'],
    dimensions: 'Hauteur: 153cm',
  },
  {
    name: 'Louis Poulsen PH Artichoke Lampe',
    shortDescription: 'Lampe Artichoke Louis Poulsen, design scandinave.',
    description: 'La lampe PH Artichoke de Louis Poulsen, un chef-d\'œuvre du design scandinave créé par Poul Henningsen. Fournit une lumière douce et non éblouissante grâce à ses 72 feuilles.',
    price: 9800.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Louis-Poulsen/001_Louis-Poulsen_PH_Artichoke_Lamp/Louis-Poulsen_PH_Artichoke_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Scandinave',
    rating: 5.0,
    stock: 5,
    colors: ['Cuivre', 'Acier inoxydable', 'Blanc'],
    materials: ['Cuivre découpé au laser', 'Acier'],
    dimensions: 'Diamètres: 48cm, 60cm, 72cm, 84cm',
  },
  {
    name: 'IKEA Tallbyn Lampe de Table',
    shortDescription: 'Lampe de table Tallbyn IKEA, style classique.',
    description: 'Lampe de table Tallbyn d\'IKEA, style classique avec un pied en métal nickelé et un abat-jour en textile. Diffuse une lumière douce et agréable.',
    price: 29.99,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/106_IKEA_Tallbyn_Table_Lamp/IKEA_Tallbyn_Table_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Classique',
    rating: 4.1,
    stock: 60,
    colors: ['Nickelé', 'Abat-jour blanc'],
    materials: ['Acier nickelé', 'Polyester'],
    dimensions: 'Hauteur: 56cm, Diam. abat-jour: 30cm',
  },
  {
    name: 'Bougeoir',
    shortDescription: 'Ensemble de bougeoirs élégants.',
    description: 'Un ensemble de bougeoirs élégants, parfaits pour créer une ambiance chaleureuse et intime. Design simple et intemporel, adapté à différents styles de décoration.',
    price: 35.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/460_Candlestick/Candlesticks_600_lq_0001-551x551.webp',
    category: 'Lampes',
    style: 'Classique',
    rating: 4.4,
    stock: 40,
    colors: ['Argenté', 'Doré', 'Noir mat'],
    materials: ['Métal', 'Verre'],
    dimensions: 'Hauteurs variables (ex: 15cm, 20cm, 25cm)',
  },
  {
    name: 'IKEA Tallbyn Lampe à Suspension',
    shortDescription: 'Lampe suspension Tallbyn IKEA, éclairage doux.',
    description: 'Lampe à suspension Tallbyn d\'IKEA, assortie à la lampe de table. Offre un éclairage général doux et confortable pour une pièce.',
    price: 39.99,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/105_IKEA_Tallbyn_Pendant_Lamp/IKEA_Tallbyn_Pendant_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Classique',
    rating: 4.2,
    stock: 45,
    colors: ['Nickelé', 'Abat-jour blanc'],
    materials: ['Acier nickelé', 'Polyester'],
    dimensions: 'Diam. abat-jour: 38cm',
  },
  {
    name: 'Louis Poulsen Patera Lampe',
    shortDescription: 'Lampe Patera Louis Poulsen, sphère lumineuse.',
    description: 'La lampe Patera de Louis Poulsen, design Øivind Slaatto, est une sphère lumineuse moderne inspirée de la suite de Fibonacci. Elle diffuse une lumière douce et agréable dans toutes les directions.',
    price: 1200.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Louis-Poulsen/004_Louis-Poulsen_Patera_Lamp/Louis-Poulsen_Patera_Lamp_1000_0001-551x551.webp',
    category: 'Lampes',
    style: 'Moderne',
    rating: 4.9,
    stock: 10,
    colors: ['Blanc'],
    materials: ['PVC découpé'],
    dimensions: 'Diamètres: 45cm, 60cm, 90cm',
  },
  // Tables (8)
  {
    name: 'Urban Wood Slab Table à manger',
    shortDescription: 'Table Urban Wood, bois massif et métal.',
    description: 'Table à manger robuste en bois massif avec un plateau épais et des pieds en métal. Parfaite pour un style industriel ou rustique.',
    price: 1250.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Urban-Wood/001_Urban-Wood_Wood_Slab_Dining_Table/Urban-Wood_Wood_Slab_Dining_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Industriel',
    rating: 4.7,
    stock: 15,
    colors: ['Bois naturel', 'Métal noir'],
    materials: ['Bois massif', 'Acier'],
    dimensions: '200cm L x 100cm P x 76cm H',
  },
  {
    name: 'Kave Home Naanim Table',
    shortDescription: 'Table Naanim Kave Home, design scandinave.',
    description: 'Table à manger Naanim de Kave Home au design épuré et scandinave, avec un plateau en bois clair et des pieds fins et élégants.',
    price: 480.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Kave-Home/010_Kave-Home_Naanim_Table/Kave-Home_Naanim_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Scandinave',
    rating: 4.5,
    stock: 25,
    colors: ['Chêne clair'],
    materials: ['Bois de chêne', 'Métal'],
    dimensions: '160cm L x 90cm P x 75cm H',
  },
  {
    name: 'Kave Home Jeanette Table d\'appoint',
    shortDescription: 'Table Jeanette Kave Home, marbre et doré.',
    description: 'Table d\'appoint Jeanette par Kave Home, un bijou de design avec son plateau en marbre véritable et sa structure métallique dorée.',
    price: 129.99,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Kave-Home/005_Kave-Home_Jeanette_Side_Table/Kave-Home_Jeanette_Side_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Moderne',
    rating: 4.8,
    stock: 30,
    colors: ['Marbre blanc', 'Doré'],
    materials: ['Marbre', 'Métal'],
    dimensions: '45cm Diam. x 50cm H',
  },
  {
    name: 'Bolia Story Table Basse',
    shortDescription: 'Table basse Story Bolia, esthétique scandinave.',
    description: 'Table basse Story de Bolia, alliant fonctionnalité et esthétique scandinave. Comprend un espace de rangement discret sous le plateau.',
    price: 390.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Bolia/008_Bolia_Story_Coffee_Table/Bolia_Story_Coffee_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Scandinave',
    rating: 4.6,
    stock: 20,
    colors: ['Chêne naturel', 'Noyer'],
    materials: ['Bois plaqué', 'Chêne massif'],
    dimensions: '110cm L x 60cm P x 40cm H',
  },
  {
    name: 'Roche Bobois Hauteville Table',
    shortDescription: 'Table Hauteville Roche Bobois, pièce sculpturale.',
    description: 'Table de repas Hauteville de Roche Bobois, une pièce sculpturale avec un piètement central original et un plateau en verre ou céramique.',
    price: 2750.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Roche-Bobois/015_Roche-Bobois_Hauteville_Table/Roche-Bobois_Hauteville_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Contemporain',
    rating: 4.9,
    stock: 10,
    colors: ['Verre transparent', 'Céramique marbrée'],
    materials: ['Verre', 'Céramique', 'Métal'],
    dimensions: '180cm L x 100cm P x 76cm H',
  },
  {
    name: 'Poliform Concorde Table',
    shortDescription: 'Table Concorde Poliform, design raffiné.',
    description: 'Table de repas Concorde par Poliform, un design raffiné en bois noble avec des détails soignés et une présence élégante.',
    price: 3600.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Poliform-Concorde/001_Poliform-Concorde_Table/Poliform-Concorde_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Moderne',
    rating: 4.8,
    stock: 8,
    colors: ['Noyer Canaletto', 'Chêne Spessart'],
    materials: ['Bois massif', 'Marbre (option)'],
    dimensions: '220cm L x 108cm P x 74cm H',
  },
  {
    name: 'Cattelan Stratos Wood Table',
    shortDescription: 'Table Stratos Wood Cattelan, design affirmé.',
    description: 'Table Stratos Wood de Cattelan Italia, caractérisée par un piètement en acier au design affirmé et un plateau en bois massif aux bords irréguliers.',
    price: 2990.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Cattelan/005_Cattelan_Stratos_Wood_Table/Cattelan_Stratos_Wood_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Contemporain',
    rating: 4.7,
    stock: 12,
    colors: ['Noyer', 'Chêne brûlé'],
    materials: ['Bois massif', 'Acier verni'],
    dimensions: '240cm L x 120cm P x 75cm H',
  },
  {
    name: 'Knoll Saarinen Table à manger',
    shortDescription: 'Table Tulipe Saarinen Knoll, classique intemporel.',
    description: 'Table Tulipe iconique de Saarinen éditée par Knoll, un classique intemporel du design du milieu du XXe siècle. Piètement central et plateau rond ou ovale.',
    price: 2250.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Knoll/003_Knoll_Saarinen_Dining_Table/Knoll_Saarinen_Dining_Table_1000_0001-551x551.webp',
    category: 'Tables',
    style: 'Vintage', 
    rating: 4.9,
    stock: 18,
    colors: ['Marbre blanc', 'Laminé blanc', 'Granit noir'],
    materials: ['Marbre', 'Laminé', 'Fonte d\'aluminium'],
    dimensions: '120cm Diam. x 72cm H',
  },
  // Armoires (8)
  {
    name: 'Keane Driftwood Armoire',
    shortDescription: 'Armoire Keane, bois flotté rustique.',
    description: 'Armoire Keane en bois flotté avec une finition naturelle texturée, apportant une touche rustique et côtière à votre chambre.',
    price: 980.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/260_Generic_Keane_Driftwood_Armoire/Generic_Keane_Driftwood_Armoire_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Rustique',
    rating: 4.5,
    stock: 10,
    colors: ['Bois flotté naturel'],
    materials: ['Bois de manguier'],
    dimensions: '100cm L x 55cm P x 190cm H',
  },
  {
    name: 'Flou Guardaroba Penderie',
    shortDescription: 'Penderie Guardaroba Flou, design épuré.',
    description: 'Penderie Guardaroba de Flou, un système modulaire au design épuré avec de grandes portes lisses pour un rangement optimisé et élégant.',
    price: 1850.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Flou/001_Flou_Guardaroba_Wardrobe/Flou_Guardaroba_Wardrobe_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Moderne',
    rating: 4.7,
    stock: 7,
    colors: ['Laqué blanc mat', 'Verre fumé'],
    materials: ['Panneaux de particules', 'Verre', 'Aluminium'],
    dimensions: '240cm L x 60cm P x 230cm H (configurable)',
  },
  {
    name: 'Modern Wardrobe Unit',
    shortDescription: 'Unité penderie moderne, finitions brillantes.',
    description: 'Unité de penderie moderne avec plusieurs compartiments, tiroirs et finitions laquées brillantes. Parfaite pour une chambre contemporaine.',
    price: 1350.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion/074_AM277_008/AM277_008_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Contemporain',
    rating: 4.4,
    stock: 12,
    colors: ['Blanc brillant', 'Gris anthracite'],
    materials: ['MDF laqué', 'Métal chromé'],
    dimensions: '180cm L x 60cm P x 210cm H',
  },
  {
    name: 'Modern Wardrobe Closet Organizer',
    shortDescription: 'Organisateur placard moderne, astucieux.',
    description: 'Organisateur de placard moderne avec une combinaison astucieuse de tiroirs, étagères et tringles pour maximiser l\'espace de rangement.',
    price: 1150.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion/078_AM277_012/AM277_012_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Fonctionnel',
    rating: 4.6,
    stock: 15,
    colors: ['Chêne clair', 'Blanc mat'],
    materials: ['Panneau de mélamine', 'Aluminium'],
    dimensions: '200cm L x 58cm P x 220cm H',
  },
  {
    name: 'IKEA BIRKELAND Penderie',
    shortDescription: 'Penderie Birkeland IKEA, style romantique.',
    description: 'Penderie IKEA Birkeland au style classique et romantique, avec des détails travaillés, des portes vitrées et une finition blanche intemporelle.',
    price: 470.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/015_IKEA_BIRKELAND_Wardrobe/IKEA_BIRKELAND_Wardrobe_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Classique',
    rating: 4.3,
    stock: 20,
    colors: ['Blanc'],
    materials: ['Panneau de fibres de bois', 'Verre trempé'],
    dimensions: '109cm L x 58cm P x 200cm H',
  },
  {
    name: 'Modern Wooden Wardrobe 02',
    shortDescription: 'Penderie bois moderne, portes coulissantes.',
    description: 'Penderie en bois moderne avec des portes coulissantes épurées, offrant un look scandinave et une grande capacité de rangement.',
    price: 1280.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion/067_AM277_001/AM277_001_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Moderne',
    rating: 4.5,
    stock: 11,
    colors: ['Frêne naturel', 'Blanc laqué'],
    materials: ['Bois massif', 'Placage bois'],
    dimensions: '160cm L x 62cm P x 215cm H',
  },
  {
    name: 'Modern Wooden Wardrobe 03',
    shortDescription: 'Grande penderie bois, design sobre.',
    description: 'Grande penderie en bois au design sobre et élégant, avec une finition minimaliste et des portes battantes. Parfaite pour une chambre contemporaine.',
    price: 1420.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion2/7397_AM112_01/AM112_01_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Minimaliste',
    rating: 4.6,
    stock: 9,
    colors: ['Noyer foncé', 'Gris mat'],
    materials: ['Placage Noyer', 'MDF'],
    dimensions: '220cm L x 60cm P x 240cm H',
  },
  {
    name: 'Ellipse Elit 3-door Wardrobe',
    shortDescription: 'Penderie Ellipse Elit, design luxueux.',
    description: 'Penderie Ellipse Elit à trois portes, offrant des finitions haut de gamme et un design moderne et luxueux pour un rangement optimal.',
    price: 2250.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/hq3dmod/5419_Ellipse_Elit_3-door_Wardrobe/Ellipse_Elit_3-door_Wardrobe_1000_0001-551x551.webp',
    category: 'Armoires',
    style: 'Contemporain',
    rating: 4.8,
    stock: 6,
    colors: ['Laqué brillant noir', 'Bois wengé'],
    materials: ['MDF laqué', 'Verre', 'Métal'],
    dimensions: '150cm L x 60cm P x 200cm H',
  },
  // Étagères (8)
  {
    name: 'Bibliothèque simple en bois',
    shortDescription: 'Bibliothèque classique, étagères robustes.',
    description: 'Bibliothèque classique en bois avec plusieurs étagères robustes, idéale pour ranger une grande collection de livres.',
    price: 190.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/476_Bookshelf/Bookshelf_600_lq_0001-551x551.webp',
    category: 'Étagères',
    style: 'Classique',
    rating: 4.3,
    stock: 30,
    colors: ['Chêne moyen', 'Noyer'],
    materials: ['Bois massif', 'Panneau de particules plaqué'],
    dimensions: '80cm L x 30cm P x 180cm H',
  },
  {
    name: 'IKEA Kallax Bibliothèque',
    shortDescription: 'Étagère Kallax IKEA, polyvalente.',
    description: 'Étagère Kallax iconique d\'IKEA, polyvalente et personnalisable avec des portes, tiroirs ou paniers. Parfaite pour tous types de rangements.',
    price: 75.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/079_IKEA_Kallax_Bookcase/IKEA_Kallax_Bookcase_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Fonctionnel',
    rating: 4.5,
    stock: 150,
    colors: ['Blanc', 'Effet chêne blanchi', 'Noir-brun'],
    materials: ['Panneau de particules', 'Peinture acrylique'],
    dimensions: '77cm L x 39cm P x 147cm H (pour 2x4 cases)',
  },
  {
    name: 'IKEA Billy Bibliothèque',
    shortDescription: 'Bibliothèque Billy IKEA, classique intemporel.',
    description: 'Bibliothèque Billy, un classique intemporel d\'IKEA pour tous les rangements de livres. Simple, fonctionnelle et adaptable.',
    price: 55.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/IKEA/078_IKEA_Billy_Bookcase/IKEA_Billy_Bookcase_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Classique',
    rating: 4.4,
    stock: 200,
    colors: ['Blanc', 'Noir-brun', 'Chêne'],
    materials: ['Panneau de particules', 'Feuille de papier'],
    dimensions: '80cm L x 28cm P x 202cm H',
  },
  {
    name: 'Charlotte Perriand Bibliothèque',
    shortDescription: 'Bibliothèque Perriand, design Mid-Century.',
    description: 'Bibliothèque inspirée du design de Charlotte Perriand, alliant une structure en métal noir et des étagères en bois. Un design Mid-Century Moderne.',
    price: 1450.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/448_Generic_Charlotte_Perriand_Bookcase/Generic_Charlotte_Perriand_Bookcase_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Vintage',
    rating: 4.8,
    stock: 8,
    colors: ['Noir', 'Bois naturel'],
    materials: ['Métal', 'Bois massif'],
    dimensions: '150cm L x 35cm P x 160cm H',
  },
  {
    name: 'Vasagle Ladder Étagère',
    shortDescription: 'Étagère échelle Vasagle, style industriel.',
    description: 'Étagère échelle Vasagle au style industriel, avec une structure en métal robuste et des tablettes en bois rustique.',
    price: 95.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Vasagle/001_Vasagle_Ladder_Shelf/Vasagle_Ladder_Shelf_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Industriel',
    rating: 4.6,
    stock: 40,
    colors: ['Brun rustique', 'Noir'],
    materials: ['Panneau d\'aggloméré', 'Acier'],
    dimensions: '60cm L x 30cm P x 170cm H',
  },
  {
    name: 'Hem Zig Zag Shelf',
    shortDescription: 'Étagère murale Zig Zag Hem, design graphique.',
    description: 'Étagère murale Zig Zag de Hem, un design ludique et graphique qui met en valeur vos objets décoratifs. En métal laqué coloré.',
    price: 260.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Hem/002_Hem_Zig_Zag_Shelf/Hem_Zig_Zag_Shelf_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Moderne',
    rating: 4.7,
    stock: 15,
    colors: ['Blanc', 'Noir', 'Jaune'],
    materials: ['Acier laqué'],
    dimensions: '60cm L x 15cm P x 50cm H',
  },
  {
    name: 'Cattelan Tokyo Bookcase',
    shortDescription: 'Bibliothèque Tokyo Cattelan, pièce sculpturale.',
    description: 'Bibliothèque Tokyo de Cattelan Italia, une pièce maîtresse sculpturale avec une structure rotative et des étagères en verre.',
    price: 3100.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/hq3dmod/4363_Cattelan_Tokyo_bookcase/Cattelan_Tokyo_bookcase_1000_0001-551x551.webp',
    category: 'Étagères',
    style: 'Contemporain',
    rating: 4.9,
    stock: 5,
    colors: ['Acier gaufré titane', 'Verre transparent'],
    materials: ['Acier', 'Verre trempé'],
    dimensions: '50cm L x 50cm P x 185cm H',
  },
  {
    name: 'Novogratz Concord Turntable Stand',
    shortDescription: 'Meuble vinyle Concord Novogratz, style rétro.',
    description: 'Meuble pour platine vinyle Concord par Novogratz, au style rétro Mid-Century, avec rangement pour disques et pieds en épingle.',
    price: 135.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Novogratz/002_Novogratz_Concord_Turntable_Stand/Novogratz_Concord_Turntable_Stand_1000_0001-551x551.webp',
    category: 'Étagères', 
    style: 'Vintage',
    rating: 4.5,
    stock: 22,
    colors: ['Noyer', 'Blanc'],
    materials: ['Panneau de particules laminé', 'Métal'],
    dimensions: '50cm L x 40cm P x 85cm H',
  },
  // Décorations (8)
  {
    name: 'Globe Terrestre Décoratif',
    shortDescription: 'Globe terrestre, touche classique intellectuelle.',
    description: 'Globe terrestre décoratif et instructif, parfait pour un bureau ou une étagère. Ajoute une touche classique et intellectuelle.',
    price: 48.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/375_Earth_Globe/Earth_Globe_600_lq_0001-551x551.webp',
    category: 'Décorations',
    style: 'Classique',
    rating: 4.6,
    stock: 50,
    colors: ['Bleu océan', 'Sépia antique'],
    materials: ['Plastique', 'Métal', 'Bois (socle)'],
    dimensions: '25cm Diam. x 35cm H',
  },
  {
    name: 'Jeu d\'Échecs Classiques en Bois',
    shortDescription: 'Jeu d\'échecs classique, pièces sculptées.',
    description: 'Jeu d\'échecs classique en bois, avec des pièces sculptées et un échiquier pliable. Idéal pour les amateurs ou comme objet de décoration.',
    price: 65.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/099_Classic_Chess_Set/Classic_Chess_Set_1000_0001-551x551.webp',
    category: 'Décorations',
    style: 'Classique',
    rating: 4.7,
    stock: 35,
    colors: ['Bois naturel et teinté'],
    materials: ['Bois'],
    dimensions: 'Échiquier: 30cm x 30cm',
  },
  {
    name: 'Cage à Oiseaux Décorative Vintage',
    shortDescription: 'Cage à oiseaux vintage, objet de charme.',
    description: 'Cage à oiseaux décorative en métal, style vintage. Parfaite pour y placer des plantes, des bougies ou comme simple objet de charme.',
    price: 38.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/374_Bird_Cage/Bird_Cage_600_lq_0001-551x551.webp',
    category: 'Décorations',
    style: 'Vintage',
    rating: 4.4,
    stock: 40,
    colors: ['Blanc vieilli', 'Bronze antique'],
    materials: ['Métal'],
    dimensions: '20cm Diam. x 40cm H',
  },
  {
    name: 'Pendule à Coucou en Bois Sculpté',
    shortDescription: 'Pendule à coucou, charme traditionnel.',
    description: 'Pendule à coucou traditionnelle en bois sculpté, évoquant le charme des chalets de la Forêt Noire. Un classique de l\'horlogerie décorative.',
    price: 125.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/1231_Wooden_Cuckoo_Clock/Wooden_Cuckoo_Clock_1000_0001-551x551.webp',
    category: 'Décorations',
    style: 'Classique',
    rating: 4.5,
    stock: 20,
    colors: ['Bois naturel sculpté'],
    materials: ['Bois'],
    dimensions: '30cm L x 15cm P x 45cm H (sans balancier)',
  },
  {
    name: 'Sablier Décoratif en Verre',
    shortDescription: 'Sablier décoratif, objet intemporel.',
    description: 'Sablier décoratif en verre et structure en bois ou métal. Un objet intemporel pour mesurer le temps ou simplement décorer.',
    price: 28.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/451_Hourglass/Hourglass_600_lq_0001-551x551.webp',
    category: 'Décorations',
    style: 'Classique',
    rating: 4.3,
    stock: 60,
    colors: ['Sable blanc', 'Sable noir', 'Bois clair', 'Métal argenté'],
    materials: ['Verre', 'Sable', 'Bois', 'Métal'],
    dimensions: '8cm Diam. x 15cm H',
  },
  {
    name: 'Chevalet d\'Artiste avec Palette',
    shortDescription: 'Chevalet d\'artiste miniature, touche artistique.',
    description: 'Chevalet d\'artiste décoratif miniature en bois, accompagné d\'une palette de peinture. Parfait pour une touche artistique dans votre intérieur.',
    price: 42.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Tools/1250_Easel_with_Painting_Palette/Easel_with_Painting_Palette_1000_0001-551x551.webp',
    category: 'Décorations',
    style: 'Bohème',
    rating: 4.6,
    stock: 25,
    colors: ['Bois naturel'],
    materials: ['Bois'],
    dimensions: 'Chevalet: 20cm L x 50cm H',
  },
  {
    name: 'Lanterne Décorative Ramadan',
    shortDescription: 'Lanterne Ramadan, ambiance exotique.',
    description: 'Lanterne décorative de style oriental, idéale pour les célébrations de Ramadan ou pour ajouter une ambiance chaleureuse et exotique.',
    price: 33.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/hq3dmod/2941_Ramadan_Lantern/Ramadan_Lantern_1000_0001-551x551.webp',
    category: 'Décorations',
    style: 'Bohème', 
    rating: 4.7,
    stock: 30,
    colors: ['Doré', 'Argenté', 'Multicolore'],
    materials: ['Métal', 'Verre coloré'],
    dimensions: '15cm L x 15cm P x 30cm H',
  },
  {
    name: 'Sooyee Corbeille à Fruits en Fil Métallique',
    shortDescription: 'Corbeille à fruits Sooyee, design géométrique.',
    description: 'Corbeille à fruits design en fil métallique noir ou doré. Une pièce moderne et géométrique pour votre cuisine ou salle à manger.',
    price: 29.90,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Generic/006_Generic_Sooyee_Metal_Wire_Fruit_Basket/Generic_Sooyee_Metal_Wire_Fruit_Basket_1000_0001-551x551.webp',
    category: 'Décorations',
    style: 'Moderne',
    rating: 4.5,
    stock: 45,
    colors: ['Noir mat', 'Doré brillant'],
    materials: ['Métal'],
    dimensions: '28cm Diam. x 12cm H',
  },
  // Mirroirs (8)
  {
    name: 'Ashley Doll House Sleigh Dresser & Miroir',
    shortDescription: 'Miroir Ashley Doll House, style Shabby Chic.',
    description: 'Ensemble commode et miroir Ashley Doll House, idéal pour une chambre d\'enfant ou un style Shabby Chic. Le miroir possède un cadre orné.',
    price: 180.00, 
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Ashley/093_Ashley_Doll_House_Sleigh_Bedroom_dresser/Ashley_Doll_House_Sleigh_Bedroom_dresser_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Classique',
    rating: 4.4,
    stock: 15,
    colors: ['Blanc antique'],
    materials: ['Bois', 'Verre'],
    dimensions: 'Miroir: 70cm L x 90cm H',
  },
  {
    name: 'Ashley Silverglade Dresser & Miroir',
    shortDescription: 'Miroir Silverglade Ashley, détails traditionnels.',
    description: 'Miroir de commode Silverglade par Ashley Furniture, avec un cadre en bois sombre et des détails traditionnels élégants.',
    price: 210.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Ashley/137_Ashley_Silverglade_Sleigh_Bedroom_Set_Dresser/Ashley_Silverglade_Sleigh_Bedroom_Set_Dresser_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Classique',
    rating: 4.5,
    stock: 12,
    colors: ['Brun foncé'],
    materials: ['Bois', 'Verre'],
    dimensions: 'Miroir: 100cm L x 80cm H',
  },
  {
    name: 'Hawthorn Hill Pivoting Shaving Mirror HH-Mirrorpivshave',
    shortDescription: 'Miroir rasage Hawthorn Hill, pivotant.',
    description: 'Miroir de rasage pivotant Hawthorn Hill, en métal chromé, avec un design classique et fonctionnel. Idéal pour une salle de bain élégante.',
    price: 120.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/3dxin/245_Hawthorn_Hill_Pivoting_Shaving_Mirror_HH-Mirrorpivshave/Hawthorn_Hill_Pivoting_Shaving_Mirror_HH-Mirrorpivshave_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Classique',
    rating: 4.6,
    stock: 25,
    colors: ['Chrome'],
    materials: ['Métal', 'Verre'],
    dimensions: '20cm Diam. x 35cm H (bras étendu)',
  },
  {
    name: 'Ashley Benjamin Dresser & Miroir',
    shortDescription: 'Miroir Benjamin Ashley, style rustique.',
    description: 'Miroir de commode Benjamin par Ashley, avec un large cadre en bois au style classique et rustique. Robuste et intemporel.',
    price: 195.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/Furniture/Ashley/038_Ashley_Benjamin_Dresser_and_Mirror/Ashley_Benjamin_Dresser_and_Mirror_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Rustique',
    rating: 4.3,
    stock: 18,
    colors: ['Brun moyen'],
    materials: ['Bois', 'Verre'],
    dimensions: 'Miroir: 90cm L x 70cm H',
  },
  {
    name: 'Antique Standing Mirror (Psyché)',
    shortDescription: 'Psyché antique, miroir sur pied.',
    description: 'Psyché antique, miroir sur pied pleine longueur avec un cadre en bois orné. Parfait pour une chambre au style vintage.',
    price: 360.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion2/6908_AM122_050/AM122_050_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Vintage',
    rating: 4.6,
    stock: 10,
    colors: ['Bois foncé', 'Bois clair'],
    materials: ['Bois', 'Verre'],
    dimensions: '60cm L x 170cm H',
  },
  {
    name: 'Table Mirror (Miroir de Table)',
    shortDescription: 'Miroir de table, simple et fonctionnel.',
    description: 'Petit miroir de table simple et fonctionnel, idéal pour une coiffeuse, une salle de bain ou comme accessoire décoratif.',
    price: 45.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/cgaxis/3426_Table_Mirror/Table_Mirror_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Minimaliste',
    rating: 4.2,
    stock: 40,
    colors: ['Argenté', 'Noir', 'Doré rose'],
    materials: ['Métal', 'Verre'],
    dimensions: '20cm L x 25cm H',
  },
  {
    name: 'Salon Mirror with Lights',
    shortDescription: 'Miroir de salon, éclairage intégré.',
    description: 'Miroir de salon professionnel avec éclairage intégré. Parfait pour les coiffeurs, maquilleurs ou pour un dressing glamour.',
    price: 280.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/cgaxis/077_Salon_Mirror_with_Lights_2/Salon_Mirror_with_Lights_2_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Moderne',
    rating: 4.7,
    stock: 12,
    colors: ['Blanc', 'Noir'],
    materials: ['Verre', 'Aluminium', 'Ampoules LED'],
    dimensions: '80cm L x 100cm H',
  },
  {
    name: 'Antique Purple Standing Mirror',
    shortDescription: 'Miroir sur pied antique, finition violette.',
    description: 'Miroir sur pied antique avec une finition violette audacieuse et un cadre ornemental. Apporte une touche bohème et vintage.',
    price: 390.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion2/6910_AM122_052/AM122_052_1000_0001-551x551.webp',
    category: 'Mirroirs',
    style: 'Vintage',
    rating: 4.5,
    stock: 9,
    colors: ['Violet', 'Or vieilli'],
    materials: ['Bois', 'Verre'],
    dimensions: '55cm L x 165cm H',
  },
  // Tapis (8)
  {
    name: 'Red Carpet 02 (Tapis Rouge)',
    shortDescription: 'Tapis rouge classique, touche de luxe.',
    description: 'Tapis rouge classique, idéal pour des événements, des couloirs ou pour ajouter une touche de couleur et de luxe.',
    price: 160.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion3/8100_Am102_78/Am102_78_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Classique', 
    rating: 4.3,
    stock: 25,
    colors: ['Rouge vif'],
    materials: ['Polypropylène', 'Velours'],
    dimensions: '120cm x 180cm',
  },
  {
    name: 'Textured Black Carpet (Tapis Noir Texturé)',
    shortDescription: 'Tapis noir texturé, sophistication moderne.',
    description: 'Tapis noir texturé, apportant profondeur et sophistication à un intérieur moderne ou minimaliste.',
    price: 210.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion3/8099_AM102_77/AM102_77_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Moderne',
    rating: 4.6,
    stock: 18,
    colors: ['Noir profond'],
    materials: ['Laine', 'Viscose'],
    dimensions: '160cm x 230cm',
  },
  {
    name: 'Brown-Orange Rug (Tapis Marron-Orange)',
    shortDescription: 'Tapis marron-orange, ambiance rétro.',
    description: 'Tapis avec des motifs dans les tons marron et orange, idéal pour une ambiance rétro, bohème ou chaleureuse.',
    price: 185.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/cgaxis/3261_Brown-Orange_Rug/Brown-Orange_Rug_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Bohème',
    rating: 4.4,
    stock: 22,
    colors: ['Marron', 'Orange', 'Beige'],
    materials: ['Coton', 'Jute'],
    dimensions: '140cm x 200cm',
  },
  {
    name: 'Round Light Grey Rug (Tapis Rond Gris Clair)',
    shortDescription: 'Tapis rond gris clair, doux et polyvalent.',
    description: 'Tapis rond gris clair, doux et polyvalent, parfait pour un style scandinave ou pour délimiter un espace avec douceur.',
    price: 130.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/cgaxis/3263_Round_Light_Grey_Rug/Round_Light_Grey_Rug_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Scandinave',
    rating: 4.5,
    stock: 30,
    colors: ['Gris clair'],
    materials: ['Polypropylène doux'],
    dimensions: '150cm Diamètre',
  },
  {
    name: 'Mischioff Tibey TB20 Carpet',
    shortDescription: 'Tapis Tibey TB20 Mischioff, design abstrait.',
    description: 'Tapis design Tibey TB20 par Mischioff, avec des motifs abstraits et contemporains. Une véritable œuvre d\'art pour le sol.',
    price: 470.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/design-connected/804_Tibey_TB20_Carpet/Tibey_TB20_Carpet_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Contemporain',
    rating: 4.8,
    stock: 10,
    colors: ['Multicolore (tons neutres et accentués)'],
    materials: ['Laine de Nouvelle-Zélande', 'Soie'],
    dimensions: '170cm x 240cm',
  },
  {
    name: 'Decorative Wooden Floor Tiles (Tapis Imitation Carrelage Bois)',
    shortDescription: 'Tapis imitation carrelage bois, rustique.',
    description: 'Grand tapis décoratif imitant des carreaux de bois anciens ou des motifs de marqueterie. Apporte une touche rustique et originale.',
    price: 290.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion3/9420_am79_092/am79_092_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Rustique',
    rating: 4.2,
    stock: 14,
    colors: ['Tons de bois variés'],
    materials: ['Vinyle imprimé', 'Polyester'],
    dimensions: '200cm x 300cm',
  },
  {
    name: 'Indoor Rectangle Soft Rug Carpet Light (Tapis Doux Rectangulaire Clair)',
    shortDescription: 'Tapis shaggy doux et clair, confort.',
    description: 'Tapis rectangulaire doux et clair, à poils longs (shaggy), apportant confort et chaleur à n\'importe quelle pièce.',
    price: 230.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/hq3dmod/5475_Indoor_rectangle_soft_rug_carpet_light/Indoor_rectangle_soft_rug_carpet_light_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Moderne',
    rating: 4.7,
    stock: 20,
    colors: ['Blanc cassé', 'Beige clair', 'Gris perle'],
    materials: ['Polyester microfibre'],
    dimensions: '160cm x 230cm',
  },
  {
    name: 'Geometric Carpet (Tapis Géométrique)',
    shortDescription: 'Tapis géométrique, motifs graphiques.',
    description: 'Tapis avec des motifs géométriques modernes et graphiques. Parfait pour dynamiser un intérieur contemporain.',
    price: 195.00,
    imageUrl: 'https://cdn.3dmodels.org/wp-content/uploads/evermotion3/8095_Am102_73/Am102_73_1000_0001-551x551.webp',
    category: 'Tapis',
    style: 'Moderne',
    rating: 4.6,
    stock: 16,
    colors: ['Noir et Blanc', 'Gris et Jaune', 'Bleu et Gris'],
    materials: ['Polypropylène', 'Laine'],
    dimensions: '150cm x 200cm',
  },
];

async function seedDB() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("Error: MONGODB_URI is not defined in your .env.local file.");
    console.error("Please ensure your MongoDB Atlas connection string is correctly set up in .env.local.");
    process.exit(1);
  }

  const client = new MongoClient(uri);

  try {
    await client.connect();
    console.log("Successfully connected to MongoDB Atlas!");

    const database = client.db("maisonmate"); 
    const productsCollection = database.collection("products");

    console.log("Deleting existing products from the collection...");
    const deleteResult = await productsCollection.deleteMany({});
    console.log(`Deleted ${deleteResult.deletedCount} products.`);

    const productsForDB = productsToSeed.map(p => {
      // Omit 'id' as MongoDB will generate '_id'
      const { ...dbProduct } = p; 
      return {
        ...dbProduct,
        price: Number(dbProduct.price),
        rating: dbProduct.rating ? Number(dbProduct.rating) : null,
        stock: dbProduct.stock ? Number(dbProduct.stock) : null,
        colors: dbProduct.colors || [],
        materials: dbProduct.materials || [],
        shortDescription: dbProduct.shortDescription || '', // Ensure shortDescription is handled
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    });

    if (productsForDB.length > 0) {
      console.log(`Attempting to insert ${productsForDB.length} products...`);
      const insertResult = await productsCollection.insertMany(productsForDB);
      console.log(`${insertResult.insertedCount} products were successfully inserted.`);
    } else {
      console.log("No products to seed.");
    }

  } catch (e) {
    console.error("An error occurred during the database seeding process:");
    console.error(e);
  } finally {
    await client.close();
    console.log("MongoDB connection closed.");
  }
}

seedDB().catch(console.error);
